"""
Supabase (PostgreSQL) data layer for the ss.ge deal monitor.
"""

import os
import sys
from datetime import datetime, timezone
from functools import lru_cache

from supabase import create_client

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS properties (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           TEXT UNIQUE NOT NULL,
    title         TEXT,
    price         TEXT,
    area_sqm      DOUBLE PRECISION,
    price_per_sqm DOUBLE PRECISION,
    location      TEXT,
    city          TEXT,
    score         INTEGER,
    summary       TEXT,
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seen_urls (
    url     TEXT PRIMARY KEY,
    seen_at TIMESTAMPTZ DEFAULT now()
);
"""


@lru_cache(maxsize=1)
def get_client():
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_KEY")
    if not url or not key:
        sys.exit("SUPABASE_URL and SUPABASE_KEY must be set.")
    return create_client(url, key)


def ensure_tables():
    """Create tables if missing."""
    db_url = os.environ.get("SUPABASE_DB_URL")
    if db_url:
        import psycopg2

        conn = psycopg2.connect(db_url)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
        conn.close()
        return
    try:
        get_client().table("properties").select("id").limit(1).execute()
        get_client().table("seen_urls").select("url").limit(1).execute()
    except Exception as e:
        print(f"Table verification check skipped: {e}")


# ------------------------------------------------------------------ scraper side

def filter_new_urls(urls):
    """Return only URLs never evaluated before."""
    if not urls:
        return []
    try:
        resp = get_client().table("seen_urls").select("url").in_("url", urls).execute()
        seen = {row["url"] for row in resp.data}
        return [u for u in urls if u not in seen]
    except Exception as e:
        print(f"Error filtering URLs: {e}")
        return urls


def mark_seen(url):
    try:
        get_client().table("seen_urls").upsert(
            {"url": url, "seen_at": datetime.now(timezone.utc).isoformat()},
            on_conflict="url",
            ignore_duplicates=True,
        ).execute()
    except Exception as e:
        print(f"Error marking URL as seen: {e}")


def save_deal(listing, analysis):
    """Insert an 8+/10 deal; duplicate URLs are silently ignored."""
    score_val = analysis.get("score") if analysis.get("score") is not None else analysis.get("rating")
    summary_val = analysis.get("summary") or analysis.get("ai_notes")

    payload = {
        "url": listing.get("url"),
        "title": listing.get("title"),
        "price": listing.get("price"),
        "location": listing.get("location"),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    if score_val is not None:
        payload["score"] = score_val
    if summary_val is not None:
        payload["summary"] = summary_val

    try:
        get_client().table("properties").upsert(
            payload,
            on_conflict="url",
            ignore_duplicates=True,
        ).execute()
    except Exception as e:
        print(f"Error saving deal: {e}")


# ---------------------------------------------------------------- dashboard side

def fetch_deals(limit=200):
    """Newest deals first, sorted safely by creation time."""
    try:
        resp = (
            get_client()
            .table("properties")
            .select("*")
            .order("created_at", desc=True)
            .limit(limit)
            .execute()
        )
        return resp.data if resp.data else []
    except Exception as e:
        print(f"Error fetching deals: {e}")
        return []