"""
Supabase (PostgreSQL) data layer for the ss.ge deal monitor.

Env vars:
  SUPABASE_URL      - https://<project-ref>.supabase.co
  SUPABASE_KEY      - service_role key (server-side only; never ship to a browser)
  SUPABASE_DB_URL   - optional: postgres:// connection string; enables automatic
                      table creation. Without it, run schema.sql once in the
                      Supabase SQL editor instead.
"""

import os
import sys
from datetime import datetime, timezone
from functools import lru_cache

from supabase import create_client

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS properties (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           TEXT UNIQUE NOT NULL,
    title         TEXT,
    price         TEXT,
    area_sqm      DOUBLE PRECISION,
    price_per_sqm DOUBLE PRECISION,
    location      TEXT,
    city          TEXT,
    rating        INTEGER,
    ai_notes      TEXT,
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seen_urls (
    url     TEXT PRIMARY KEY,
    seen_at TIMESTAMPTZ DEFAULT now()
);
"""


@lru_cache(maxsize=1)
def get_client():
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_KEY")
    if not url or not key:
        sys.exit("SUPABASE_URL and SUPABASE_KEY must be set. See README.md.")
    return create_client(url, key)


def ensure_tables():
    """Create tables if missing. Uses the direct Postgres connection when
    SUPABASE_DB_URL is set; otherwise just verifies the tables exist and
    points at schema.sql if they don't (the REST API can't run DDL)."""
    db_url = os.environ.get("SUPABASE_DB_URL")
    if db_url:
        import psycopg2

        conn = psycopg2.connect(db_url)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
        conn.close()
        return
    try:
        get_client().table("properties").select("id").limit(1).execute()
        get_client().table("seen_urls").select("url").limit(1).execute()
    except Exception as e:
        sys.exit(
            "Supabase tables not found (and SUPABASE_DB_URL not set, so they "
            "can't be auto-created).\nFix: open your Supabase project -> SQL "
            f"Editor -> paste and run schema.sql.\nUnderlying error: {e}"
        )


# ------------------------------------------------------------------ scraper side

def filter_new_urls(urls):
    """Return only URLs never evaluated before (one batched query)."""
    if not urls:
        return []
    resp = get_client().table("seen_urls").select("url").in_("url", urls).execute()
    seen = {row["url"] for row in resp.data}
    return [u for u in urls if u not in seen]


def mark_seen(url):
    get_client().table("seen_urls").upsert(
        {"url": url, "seen_at": datetime.now(timezone.utc).isoformat()},
        on_conflict="url",
        ignore_duplicates=True,
    ).execute()


def save_deal(listing, analysis):
    """Insert an 8+/10 deal; duplicate URLs are silently ignored."""
    get_client().table("properties").upsert(
        {
            "url": listing["url"],
            "title": listing["title"],
            "price": listing["price"],
            "area_sqm": listing["area_sqm"],
            "price_per_sqm": analysis.get("price_per_sqm"),
            "location": listing["location"],
            "city": analysis.get("city"),
            "rating": analysis.get("score"),
            "ai_notes": analysis.get("summary"),
            "created_at": datetime.now(timezone.utc).isoformat(),
        },
        on_conflict="url",
        ignore_duplicates=True,
    ).execute()


# ---------------------------------------------------------------- dashboard side

def fetch_deals(limit=200):
    """Newest high-scoring deals first, for the Streamlit feed."""
    resp = (
        get_client()
        .table("properties")
        .select("*")
        .order("created_at", desc=True)
        .order("rating", desc=True)
        .limit(limit)
        .execute()
    )
    return resp.data
