-- Run this once in Supabase -> SQL Editor (or set SUPABASE_DB_URL and let
-- database.py create the tables automatically).

CREATE TABLE IF NOT EXISTS properties (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           TEXT UNIQUE NOT NULL,
    title         TEXT,
    price         TEXT,
    area_sqm      DOUBLE PRECISION,
    price_per_sqm DOUBLE PRECISION,
    location      TEXT,
    city          TEXT,
    rating        INTEGER,
    ai_notes      TEXT,
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seen_urls (
    url     TEXT PRIMARY KEY,
    seen_at TIMESTAMPTZ DEFAULT now()
);
